### ISSUE TITLE
Add support for anonymous functions (eval)

### ISSUE THREAD

**Issue by eriwen** [stacktracejs/error-stack-parser#32]
@genielabs commented on [Sun Jun 26 2016](https://github.com/stacktracejs/stackframe/issues/12)

Given an error stack like this one:

```
ReferenceError: a is not defined
    at $$.onStart (eval at <anonymous> (http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6851:25), <anonymous>:32:7)
    at $$.RenderWidget (http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6770:36)
    at $$.RenderView (http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6757:12)
    at http://localhost:8080/hg/html/js/homegenie.webapp.js?version=r525:6879:24
    at Object.$.ajax.success (http://localhost:8080/hg/html/js/homegenie.api.js?version=r525:724:21)
    at l (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:3:24881)
    at Object.c.fireWith [as resolveWith] (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:3:25702)
    at k (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:5:4919)
    at XMLHttpRequest.<anonymous> (http://localhost:8080/hg/html/js/jquery-2.0.2.min.js:5:8723)
```

stackframe will currently ignore the eval `<anonymous>:32:7` at the end of the first stack element, which is the real source of the error at line 32, column 7.
It will indeed report **stack[0]** with line **6851** and column **25**.

---

@eriwen commented on [Fri Nov 25 2016](https://github.com/stacktracejs/stackframe/issues/12#issuecomment-263024367)

@genielabs Stackframe itself handles `eval` origins as you can `setEvalOrigin(Stackframe)`. However, `error-stack-parser` does not set eval origins yet, so I'm going to move this issue to that project. Thanks for submitting.

**Comment by aight8** [comment]
Is there currently ONE existing node stack parser which can handle stacks which contains eval lines? I don't found any.

**Comment by cjaeriksson** [comment]
Any updates on this ?

**Comment by eriwen** [comment]
@cjaeriksson No, I'm afraid.

**Comment by ForsakenHarmony** [comment]
Hmm yes, 8 years later, and I still can't find a library that can parse it (and the PR here was never completed) 😢
