### ISSUE TITLE
Some failing tests

### ISSUE THREAD

**Issue by fresheneesz** [stacktracejs/error-stack-parser#9]
I wrote some failing tests based tests I've had working for my stackinfo project. I'm blocked on using the new version of stacktrace.js until they're fixed, so I'd like to do as much as I can to get them fixed up.

Error objects to be included in captured-errors.js
```javascript
CapturedExceptions.CHROME_40A = { // I'm assuming here that the numbers are the version (this is version 40)
    message: "who cares",
    name: "Error",
    stack: "Error: who cares\n" +
    "    H()@http://localhost:8100/:47:25\n" +
    "    ProtoObjectFactory.<anonymous> (http://localhost:8001/git/frontend/test/allTestsFE.bundle.js:1459:20)\n" +
    "    (?)()@http://localhost:8001/git/frontend/test/allTestsFE.bundle.js:79:15\n" +
    "    Object.module.exports.test.TabBar.buttons.callback [as click] (http://localhost:8001/git/frontend/test/allTestsFE.bundle.js:1546:9)"
}

// note, this comes from the same code as FIREFOX_35_B
CapturedExceptions.CHROME_40B = { // I'm assuming here that the numbers are the version (this is version 40)
    message: "who cares",
    name: "Error",
    stack: "Error\n"+
    "    at Object.StackTrace$$get [as get] (http://localhost:8100/generatedBuild/stackinfo.umd.js:3788:23)\n"+
    "    at 21.module.exports (http://localhost:8100/generatedBuild/stackinfo.umd.js:3923:38)\n"+
    "    at http://localhost:8100/:47:13\n"+
    "    at http://localhost:8100/test/moar.js:12:9\n"+
    "    at x (http://localhost:8100/test/moar.js:7:5)\n"+
    "    at moar (http://localhost:8100/test/moar.js:2:5)\n"+
    "    at H (http://localhost:8100/:46:9)\n"+
    "    at http://localhost:8100/:41:13\n"+
    "    at Array.forEach (native)\n"+
    "    at G (http://localhost:8100/:40:14)"
}

CapturedExceptions.FIREFOX_35 = {             // I'm assuming here that the numbers are the version (this is version 35)
    message: "whatever",
    name: "Error",
    stack: "ReferenceError: whatever\n" +
    "   (?)()@http://localhost:8100/test.web.bundle.js:75\n" +
    "   module.exports/req.onreadystatechange@http://localhost:8001/git/frontend/test/generated/allTestsFE.bundle.js:5943:1\n" +
    "   module.exports<.getSourceMapObject@http://localhost:8001/git/frontend/test/generated/allTestsFE.bundle.js:4970:10",
    fileName: "http://path/to/file.js",
    lineNumber: 75
};

// note, this comes from the same code as CHROME_40B
CapturedExceptions.FIREFOX_35_B = {           // I'm assuming here that the numbers are the version (this is version 35)
    message: "whatever",
    name: "Error",
    stack: "StackTrace$$get@http://localhost:8100/generatedBuild/stackinfo.umd.js:3788:23\n" +
        "[21]</module.exports@http://localhost:8100/generatedBuild/stackinfo.umd.js:3923:27\n" +
        "H/<@http://localhost:8100/:47:13\n" +
        "gen/<@http://localhost:8100/test/moar.js:12:9\n" +
        "x@http://localhost:8100/test/moar.js:7:5\n" +

        "moar@http://localhost:8100/test/moar.js:2:5\n" +
        "H@http://localhost:8100/:46:9\n" +
        "G/<@http://localhost:8100/:41:13\n" +
        "G@http://localhost:8100/:40:10\n" +
        "F<[6]/<@http://localhost:8100/:34:21\n" +


        "E.fn1@http://localhost:8100/:27:13\n" +
        "D@http://localhost:8100/:22:9\n" +
        "C@http://localhost:8100/:18:9\n" +
        "B@http://localhost:8100/:14:9\n" +
        "A@http://localhost:8100/:10:9\n" +

        "unittest</<@http://localhost:8100/:156:13\n" +
        "testGroup/runTest@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3746:17\n" +
        "[18]</module.exports<.runTestGroup@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3465:9\n" +
        "testGroup@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3752:9\n" +
        "[19]</module.exports/UnitTester.prototype.test@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3881:17\n" +


        "unittest<@http://localhost:8100/:153:9\n" +
        "testGroup/runTest@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3746:17\n" +
        "[18]</module.exports<.runTestGroup@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3465:9\n" +
        "testGroup@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3752:9\n" +
        "[19]</module.exports/UnitTester.prototype.test@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3881:17\n" +

        "runTest@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3649:13\n" +
        "[19]</module.exports/UnitTest</this.init/<@http://localhost:8100/node_modules/deadunit/browserPackage/deadunit.browser.gen.umd.js:3593:17\n",
    fileName: "http://localhost:8100/generatedBuild/stackinfo.umd.js",
    lineNumber: 3788,
    columnNumber: 22
};



CapturedExceptions.IE_11_C = {
    message: "whatever",
    name: "ReferenceError",
    stack: "ReferenceError: whatever\n" +
    "   {anonymous}()@(http://localhost:8100/:47:13)\n" +
    "   x@http://localhost:8100/test/moar.js:7:5",
    description: "whatever",
    number: -2146823279
};
```

Specs to be added to error-stack-parser-spec.js

```javascript

        it('should parse V8 Error.stack entries of various types', function () {
            var stackFrames = unit.parse(CapturedExceptions.CHROME_38);
            expect(stackFrames).toBeTruthy();
            expect(stackFrames.length).toBe(10);
            expect(stackFrames[0]).toMatchStackFrame(['Object.StackTrace$$get', undefined, 'http://localhost:8100/generatedBuild/stackinfo.umd.js', 3788, 23]);
            expect(stackFrames[1]).toMatchStackFrame(['21.module.exports', undefined, "http://localhost:8100/generatedBuild/stackinfo.umd.js", 3923, 38]);
            expect(stackFrames[2]).toMatchStackFrame([undefined, undefined, "http://localhost:8100/", 47, 13]);
            expect(stackFrames[3]).toMatchStackFrame([undefined, undefined, "http://localhost:8100/test/moar.js", 12, 9]);
            expect(stackFrames[4]).toMatchStackFrame(['x', undefined, 'http://localhost:8100/test/moar.js', 7, 5]);
            expect(stackFrames[5]).toMatchStackFrame(['moar', undefined, 'http://localhost:8100/test/moar.js', 2, 5]);
            expect(stackFrames[6]).toMatchStackFrame(['H', undefined, 'http://localhost:8100/', 46, 9]);
            expect(stackFrames[7]).toMatchStackFrame([undefined, undefined, 'http://localhost:8100/', 41, 13]);
            expect(stackFrames[8]).toMatchStackFrame(['Array.forEach', undefined, undefined, undefined, undefined]);
            expect(stackFrames[9]).toMatchStackFrame(['G', undefined, 'http://localhost:8100/', 40, 14]);
        });

        it('should parse V8 Error.stack entries of other various types', function () {
            var stackFrames = unit.parse(CapturedExceptions.CHROME_37);
            expect(stackFrames).toBeTruthy();
            expect(stackFrames.length).toBe(4);
            expect(stackFrames[0]).toMatchStackFrame(['H', undefined, 'http://localhost:8100/', 47, 25]);
            expect(stackFrames[1]).toMatchStackFrame(['ProtoObjectFactory.<anonymous>', undefined, "http://localhost:8001/git/frontend/test/allTestsFE.bundle.js", 1459, 20]);
            expect(stackFrames[2]).toMatchStackFrame([undefined, undefined, "http://localhost:8001/git/frontend/test/allTestsFE.bundle.js", 79, 15]);
            expect(stackFrames[3]).toMatchStackFrame(['Object.module.exports.test.TabBar.buttons.callback', undefined, "http://localhost:8001/git/frontend/test/allTestsFE.bundle.js", 1546, 9]);
        });

        it('should parse Firefox 35 Error.stack', function () {
            var stackFrames = unit.parse(CapturedExceptions.FIREFOX_35);
            expect(stackFrames).toBeTruthy();
            expect(stackFrames.length).toBe(3);
            expect(stackFrames[0]).toMatchStackFrame(['(?)()', undefined, "http://localhost:8100/test.web.bundle.js", 75, undefined]);
            expect(stackFrames[1]).toMatchStackFrame(['module.exports/req.onreadystatechange', undefined, "http://localhost:8001/git/frontend/test/generated/allTestsFE.bundle.js", 5943, 1]);
            expect(stackFrames[2]).toMatchStackFrame(['module.exports<.getSourceMapObject', undefined, "http://localhost:8001/git/frontend/test/generated/allTestsFE.bundle.js", 4970, 10]);
        });

        it('should parse another Firefox 35 Error.stack', function () {
            var stackFrames = unit.parse(CapturedExceptions.FIREFOX_35_B);
            expect(stackFrames).toBeTruthy();
            expect(stackFrames.length).toBe(27);

            expect(stackFrames[0]).toMatchStackFrame(['StackTrace$$get', undefined, "http://localhost:8100/generatedBuild/stackinfo.umd.js", 3788, 23]);
            expect(stackFrames[1]).toMatchStackFrame(['[21]</module.exports', undefined, "", 3923, 27]);
            expect(stackFrames[2]).toMatchStackFrame(['H', undefined, "", 47, 13]);
            expect(stackFrames[3]).toMatchStackFrame(['gen', undefined, "", 12, 9]);
            expect(stackFrames[4]).toMatchStackFrame(['x', undefined, "", 7, 5]);

            expect(stackFrames[5]).toMatchStackFrame(['moar', undefined, "", 2, 5]);
            expect(stackFrames[6]).toMatchStackFrame(['H', undefined, "", 46, 9]);
            expect(stackFrames[7]).toMatchStackFrame(['G', undefined, "", 41, 13]);
            expect(stackFrames[8]).toMatchStackFrame(['G', undefined, "", 40, 10]);
            expect(stackFrames[9]).toMatchStackFrame(['F', undefined, "", 34, 21]);


            expect(stackFrames[10]).toMatchStackFrame(['E.fn1', undefined, "", 27, 13]);
            expect(stackFrames[11]).toMatchStackFrame(['D', undefined, "", 22, 9]);
            expect(stackFrames[12]).toMatchStackFrame(['C', undefined, "", 18, 9]);
            expect(stackFrames[13]).toMatchStackFrame(['B', undefined, "", 14, 9]);
            expect(stackFrames[14]).toMatchStackFrame(['A', undefined, "", 10, 9]);

            expect(stackFrames[15]).toMatchStackFrame(['unittest', undefined, "", 156, 13]);
            expect(stackFrames[16]).toMatchStackFrame(['testGroup/runTest', undefined, "", 3746, 17]);
            expect(stackFrames[17]).toMatchStackFrame(['[18]</module.exports<.runTestGroup', undefined, "", 3465, 9]);
            expect(stackFrames[18]).toMatchStackFrame(['testGroup', undefined, "", 3752, 9]);
            expect(stackFrames[19]).toMatchStackFrame(['[19]</module.exports/UnitTester.prototype.test', undefined, "", 3881, 17]);


            expect(stackFrames[20]).toMatchStackFrame(['unittest', undefined, "", 153, 9]);
            expect(stackFrames[21]).toMatchStackFrame(['testGroup/runTest', undefined, "", 3746, 17]);
            expect(stackFrames[22]).toMatchStackFrame(['[18]</module.exports<.runTestGroup', undefined, "", 3465, 9]);
            expect(stackFrames[23]).toMatchStackFrame(['testGroup', undefined, "", 3752, 9]);
            expect(stackFrames[24]).toMatchStackFrame(['[19]</module.exports/UnitTester.prototype.test', undefined, "", 3881, 17]);

            expect(stackFrames[25]).toMatchStackFrame(['runTest', undefined, "", 3649, 13]);
            expect(stackFrames[26]).toMatchStackFrame(['[19]</module.exports/UnitTest</this.init/<', undefined, "", 3593, 17]);
        });



        it('should parse other IE 11 Error stacks', function () {
            var stackFrames = unit.parse(CapturedExceptions.IE_11_C);
            expect(stackFrames).toBeTruthy();
            expect(stackFrames.length).toBe(2);
            expect(stackFrames[0]).toMatchStackFrame(['{anonymous}()', undefined, "http://localhost:8100/", 47, 13]);
            expect(stackFrames[1]).toMatchStackFrame(['x', undefined, "http://localhost:8100/test/moar.js", 7, 5]);
        });
```

I can show you the code I'm  using to parse these things if you want - they're done very differently from how you're doing it tho.

Btw I'd recommend that if you can't parse a line, instead of completely failing the whole parse, you include an object that contains the error or something. You're never going to be able to parse every kind of stack trace, especially since browsers may change their formats. This would allow the user to either use the original raw traceline, print some kind of error message just for that line, or do whatever kind of handling they like, without interrupting the rest of the operation. Otherwise you're gonna get a lot of cases where stacktrace.js tells users "can't get a stacktrace for you" when really you mean "I can't figure out everything about this particular line in the stacktrace". 

I see that in some cases (for example, in parseFFOrSafari) you are clipping out some of the stack trace lines using filter. I really don't think this is the right thing to do - you're throwing away information that could be useful to the end user. Why throw it away? If you can't parse it, add a StackFrame that indicates you couldn't parse it. You should also put the raw line somewhere in the StackFrame so users can access that if they want / need to (say if stacktrace.js can't properly parse the line).

**Comment by fresheneesz** [comment]
How do you develop with karma? Karma's website isn't very helpful in this regard. Some of the tests that are printing out (which I would assume are failing tests) look like they're getting the right values, so maybe they're not actually failing? How can I run the tests in browser in such a way where I can step through the running code so I can debug stuff?

**Comment by eriwen** [comment]
@fresheneesz As long as you run `npm install karma -g` you should be able to run `make test` and everything *should* just work. 

Personally, I have it setup through WebStorm so I can continuously run karma while developing.

**Comment by fresheneesz** [comment]
I've run `make test` and it runs the tests. But that involves opening a browser window, running the tests, then closing. If I want to set breakpoints in the test so I can debug why things are failing, how do I do that?

**Comment by eriwen** [comment]
I haven't needed to find out since I just use WebStorm for debugging. 

This seems promising: http://bahmutov.calepin.co/debugging-karma-unit-tests.html

**Comment by fresheneesz** [comment]
Heyy, that's super helpful. I can just run `karma start karma.conf.js --browsers=Chrome --single-run=false --debug` and reload the page as if it were a normally served webpage (i guess it kinda is), and any breakpoints i set are hit. I think it'd be helpful to any prospective contributors if you added that link or some instructions of some kind into the contributing.md file. I use intellij too, so instructions on how to do it through webstorm the way you do would also be helpful. Thanks!

**Comment by fresheneesz** [comment]
@eriwen Would you accept a pull request for these tests if I updated the code to support those cases?

**Comment by eriwen** [comment]
Yes, as long as we didn't have to change how parsing works drastically.

**Comment by fresheneesz** [comment]
Ok, i'll probably work on it this week then.

**Comment by fresheneesz** [comment]
I'm trying to run the karma tests with the normal `karma start`, but it just opens firefox and then stops. It says Karma v0.12.31 is connected and that phantomjs and firefox are "idle". It works if i use flags to run just chrome like i mentioned above.

In any case, I went through my tests and noticed that some of the tracelines i was testing off of aren't valid tracelines. I'm guessing the old version of stacktrace.js changed some tracelines before returning them. So seems like the extra tests above, after corrected, don't find any bugs in there. If you feel like they'd still be useful to include, I committed them on my fork: https://github.com/fresheneesz/error-stack-parser/commits/master .

**Comment by fresheneesz** [comment]
@eriwen I'm still wondering why you're using `filter` for `parseFFOrSafari` and `parseOpera11`. I'm worried those might be removing tracelines simply because error-stack-parser doesn't know how to parse the line (or the whole line) yet.
