### ISSUE TITLE
Browser error?

### ISSUE THREAD

**Issue by mauricio-lomeli-planview** [stacktracejs/error-stack-parser#90]
## Expected Behavior
Show the stack trace

## Current Behavior
```
error-stack-parser.js:31 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'parseV8OrIE')
    at ErrorStackParser$$parse (error-stack-parser.js:31:1)
    at StatusPageErrorBoundary.render (StatusPageProvider.tsx:24:1)
    at finishClassComponent (react-dom.development.js:17485:1)
    at updateClassComponent (react-dom.development.js:17435:1)
    at beginWork (react-dom.development.js:19073:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at eval (index.js:1:1)
    at Object.with (index.js:1:1)
    at HTMLUnknownElement.r (index.js:1:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
```

![Screenshot 2023-06-13 at 3 18 37 PM](https://github.com/stacktracejs/error-stack-parser/assets/123599290/da343233-1590-4424-93f3-88a51dbfe7a9)

## Steps to Reproduce (for bugs)

```const frame = parse(new Error('BOOM'));```

## Context
Just want to read the error in a parsed format.

## Your Environment
* Package version: latest
* Browser name and version: Chrome latest
* OS version (desktop or mobile): MacOS
* Link to your project: N/A

## Possible Solution
None

**Comment by RPGillespie6** [comment]
Seems like only the minified version is properly bundled.
